# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Porteden < Formula
  desc "Calendar firewall & management CLI for PortEden"
  homepage "https://porteden.com"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/porteden/cli/releases/download/v0.3.1/porteden_0.3.1_darwin_amd64.tar.gz"
      sha256 "dbf4c66af5184681847620de14f4aff44609ca349fd4854247011e4b185e9b8d"

      def install
        bin.install "porteden"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/porteden/cli/releases/download/v0.3.1/porteden_0.3.1_darwin_arm64.tar.gz"
      sha256 "a180dcd1d77c0fdd392584727690e439158b42fae3756438acdb82d85172dc80"

      def install
        bin.install "porteden"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/porteden/cli/releases/download/v0.3.1/porteden_0.3.1_linux_amd64.tar.gz"
      sha256 "698bb2a57754d40eac15e757e45809c596347815f7296bb02bcbc7c7504b60b9"
      def install
        bin.install "porteden"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/porteden/cli/releases/download/v0.3.1/porteden_0.3.1_linux_arm64.tar.gz"
      sha256 "2aa686cdd50b99ab89ff0c48455adfe421f93b932915e3d3788271dce4c1f36f"
      def install
        bin.install "porteden"
      end
    end
  end

  test do
    system "#{bin}/porteden", "--version"
  end
end
